name: "workshop github actions"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  lint: # Any name you want 
    name: Ansible Lint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install node
        uses: actions/setup-node@v4.0.4

      - name: Install dependencies
        run: npm run setup

      - name: Run Lint
        run: npm run lint 

      - name: Run Formatter
        run: npm run format:write
